# Generated by Django 5.0.7 on 2024-07-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("SAVINGS", "Savings"),
                            ("CURRENT", "Current"),
                            ("SALARY", "Salary"),
                            ("FD", "Fixed Deposit"),
                            ("RD", "Recurring Deposit"),
                            ("NRI", "NRI"),
                        ],
                        max_length=50,
                    ),
                ),
                ("pan_number", models.CharField(max_length=10, unique=True)),
                ("adhaar_number", models.CharField(max_length=12, unique=True)),
                (
                    "other_documents",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="<django.db.models.fields.CharField>_<django.db.models.fields.CharField>_documents/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compliances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
