# Generated by Django 5.0.7 on 2024-07-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complicanceAI", "0002_bankaccount_bank_statement"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="insights",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
