# Generated by Django 5.0.7 on 2024-07-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("complicanceAI", "0003_bankaccount_insights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_statement",
            field=models.FileField(blank=True, null=True, upload_to="bankStatements/"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="insights",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="other_documents",
            field=models.FileField(blank=True, null=True, upload_to="OtherDocuments/"),
        ),
    ]
