# Generated by Django 5.0.7 on 2024-07-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("complicanceAI", "0004_alter_bankaccount_bank_statement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("SAVINGS", "Savings"),
                    ("CURRENT", "Current"),
                    ("SALARY", "Salary"),
                    ("FixedDeposit", "FixedDeposit"),
                    ("RecurringDeposit", "RecurringDeposit"),
                    ("NRI", "NRI"),
                ],
                max_length=50,
            ),
        ),
    ]
